apiVersion: v1
kind: Pod
metadata:
  name: promocode-factory-api
  labels:
    app: factory-api
    version: "12.2020"
spec:
  containers:
  - name: promocode-factory-api
    image: ghcr.io/aleksandrnew/otus-k8s-dev/promocode-factory-api:12.2020
    ports:
      - name: http
        containerPort: 80
        protocol: TCP
    livenessProbe:
      exec:
        command:
         - cat
         - /app/web.config
      initialDelaySeconds: 5
      timeoutSeconds: 1 # Default is 1
      periodSeconds: 5 # Default is 10
      failureThreshold: 2 # Default is 3
    readinessProbe:
      exec:
        command:
         - cat
         - /app/web.config
      initialDelaySeconds: 10
      timeoutSeconds: 5 # Default is 1
      periodSeconds: 30 # Default is 10
      failureThreshold: 5 # Default is 3
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 100m
        memory: 256Mi
