apiVersion: v1
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: managed-premium
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
parameters:
  storageaccounttype: Premium_LRS
  kind: Managed
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 5Gi
---
kind: Pod
metadata:
  name: promocode-factory-api
  labels:
    app: factory-api
    version: "12.2020"
spec:
  containers:
  - name: promocode-factory-api
    image: docker.pkg.github.com/aleksandrnew/otus-k8s-dev/promocode-factory-api:12.2020
    ports:
      - name: http
        containerPort: 80
        protocol: TCP
    volumeMounts:
    - mountPath: "/mnt/azure"
      name: volume
  volumes:
  - name: volume
    persistentVolumeClaim:
      claimName: azure-managed-disk