apiVersion: apps/v1
kind: Deployment
metadata:
  name: promocode-factory-api
  labels:
    app: factory-api
    version: "12.2020"
  annotations:
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: promocode-factory-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: promocode-factory-api
    spec:
      volumes:
      - name: data
        hostPath:
          # directory location on host
          path: /tmp
          # this field is optional
          type: Directory
      containers:
      - name: promocode-factory-api
        image: ghcr.io/aleksandrnew/otus-k8s-dev/promocode-factory-api:12.2020
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /db
