apiVersion: v1
kind: ConfigMap
metadata:
  name: promocode-factory-api-settings
  labels:
    app: factory-api
    version: "12.2020"
    env: dev
data:
  appsettings.json: |
    {
         "LogLevel": {
           "Default": "Information",
           "Microsoft": "Warning",
           "Microsoft.Hosting.Lifetime": "Information"
         }
       },
       "AllowedHosts": "*"
    }
