apiVersion: v1
kind: Pod
metadata:
  name: promocode-factory-api
  labels:
    app: factory-api
    version: "12.2020"
spec:
  containers:
  - name: promocode-factory-api
    image: ghcr.io/aleksandrnew/otus-k8s-dev/promocode-factory-api:12.2020
    ports:
      - name: http
        containerPort: 80
        protocol: TCP
    env:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-passwords-secret
          key: db-password
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 100m
        memory: 256Mi
